/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-07-21 05:33:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("<link href=\"../../resources/css/user/userJoin.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body >\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <div class=\"joinbox\">\n");
      out.write("  <div class=\"logobox\">\n");
      out.write("    <h2 class=\"logotitle\">MARKUP</h2>\n");
      out.write("    <span class=\"logosub\">MINECRAFT-LIFE</span>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"formbox\">\n");
      out.write("    <form action=\"/member/join\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("      <div style=\"width: 500px;\">\n");
      out.write("        <div class=\"accordion\" id=\"accordionPanelsStayOpenExample\">\n");
      out.write("          <div class=\"accordion-item\">\n");
      out.write("            <h2 class=\"accordion-header\" id=\"panelsStayOpen-headingOne\">\n");
      out.write("              <button class=\"accordion-button\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#panelsStayOpen-collapseOne\" aria-expanded=\"true\" aria-controls=\"panelsStayOpen-collapseOne\">\n");
      out.write("                아이디 & 비밀번호\n");
      out.write("              </button>\n");
      out.write("            </h2>\n");
      out.write("            <div id=\"panelsStayOpen-collapseOne\" class=\"accordion-collapse collapse show\" aria-labelledby=\"panelsStayOpen-headingOne\">\n");
      out.write("              <div class=\"accordion-body\">\n");
      out.write("              <div class=\"jointitle\">아이디</div>\n");
      out.write("                <input type=\"text\" name=\"id\" placeholder=\"아이디를 입력해주세요.\" id=\"joinid\">\n");
      out.write("                <button type=\"button\" id=\"duplicateCheck\">중복확인</button> <br>\n");
      out.write("                <div class=\"ment\"><span id=\"idMent\" class=\"spanment\"></span></div>\n");
      out.write("                <div class=\"jointitle\">비밀번호</div>\n");
      out.write("                <input type=\"password\" name=\"pw\" placeholder=\"비밀번호를 입력해주세요.\" id=\"pw\"> <br>\n");
      out.write("                <div class=\"ment\"><span id=\"pwMent2\" class=\"spanment\"></span></div>\n");
      out.write("                <div class=\"jointitle\">비밀번호 확인</div>\n");
      out.write("                <input type=\"password\" id=\"pwCheck\"><br>\n");
      out.write("                <div class=\"ment\"><span id=\"pwMent\" class=\"spanment\"></span></div>\n");
      out.write("                <input type=\"file\" name=\"img\" id=\"file\" accept=\"image/png, image/jpg, image/jpeg, image/bmp, image/gif\" style=\"display: none\" onchange=\"previewImage(this)\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"accordion-item\">\n");
      out.write("            <h2 class=\"accordion-header\" id=\"panelsStayOpen-headingTwo\">\n");
      out.write("              <button class=\"accordion-button collapsed buttongroup\" id=\"firstBtn\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#panelsStayOpen-collapseTwo\" aria-expanded=\"false\" aria-controls=\"panelsStayOpen-collapseTwo\">\n");
      out.write("                프로필 설정\n");
      out.write("              </button>\n");
      out.write("            </h2>\n");
      out.write("            <div id=\"panelsStayOpen-collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"panelsStayOpen-headingTwo\">\n");
      out.write("              <div class=\"accordion-body\">\n");
      out.write("				<div class=\"imgbox\">\n");
      out.write("                <div id=\"previewbox\">\n");
      out.write("                <img alt=\"\" src=\"../../resources/images/profile/24.png\" id=\"preview\">\n");
      out.write("                </div>\n");
      out.write("               <button type=\"button\" class=\"btn btn-primary profileBtn\" data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\" id=\"close\">\n");
      out.write("                  프로필 사진 설정\n");
      out.write("                </button>\n");
      out.write("				</div>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                <br>\n");
      out.write("                <div class=\"joincontainer\">\n");
      out.write("                  <div class=\"jointitle\">닉네임</div>\n");
      out.write("                  <input type=\"text\" name=\"name\" id=\"name\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"joincontainer\">\n");
      out.write("                  <div class=\"jointitle\">이메일</div>\n");
      out.write("                  <input type=\"email\" name=\"email\" id=\"email\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"joincontainer\">\n");
      out.write("                  <div class=\"jointitle\">소개글</div>\n");
      out.write("                  <textarea rows=\"3\" cols=\"30\" name=\"ucontent\" placeholder=\"안녕하세요 :)\" id=\"content\"></textarea>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"accordion-item\">\n");
      out.write("            <h2 class=\"accordion-header\" id=\"panelsStayOpen-headingThree\">\n");
      out.write("              <button class=\"accordion-button collapsed buttongroup\" type=\"button\" id=\"secondBtn\" data-bs-toggle=\"collapse\" data-bs-target=\"#panelsStayOpen-collapseThree\" aria-expanded=\"false\" aria-controls=\"panelsStayOpen-collapseThree\">\n");
      out.write("                관심분야를 선택해주세요.\n");
      out.write("              </button>\n");
      out.write("            </h2>\n");
      out.write("            <div id=\"panelsStayOpen-collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"panelsStayOpen-headingThree\">\n");
      out.write("              <div class=\"accordion-body\">\n");
      out.write("              <div class=\"tagbox\">\n");
      out.write("              <label for=\"checkbox1\">\n");
      out.write("                <input type=\"checkbox\" value=\"광물\" id=\"checkbox1\" name=\"utag\" class=\"tags\">광물</label>\n");
      out.write("                 <label for=\"checkbox2\">\n");
      out.write("                <input type=\"checkbox\" value=\"pvp\" id=\"checkbox2\" name=\"utag\" class=\"tags\">pvp</label>\n");
      out.write("                 <label for=\"checkbox3\">\n");
      out.write("                <input type=\"checkbox\" value=\"야생\" id=\"checkbox3\" name=\"utag\" class=\"tags\">야생</label>\n");
      out.write("                 <label for=\"checkbox4\">\n");
      out.write("                <input type=\"checkbox\" value=\"건축\" id=\"checkbox4\" name=\"utag\" class=\"tags\">건축</label>\n");
      out.write("                 <label for=\"checkbox5\">\n");
      out.write("                <input type=\"checkbox\" value=\"모드\" id=\"checkbox5\" name=\"utag\" class=\"tags\">모드</label>\n");
      out.write("                 <label for=\"checkbox6\">\n");
      out.write("                <input type=\"checkbox\" value=\"플러그인\" id=\"checkbox6\" name=\"utag\" class=\"tags\">플러그인</label>\n");
      out.write("                 <label for=\"checkbox7\">\n");
      out.write("                <input type=\"checkbox\" value=\"스킨\" id=\"checkbox7\" name=\"utag\" class=\"tags\">스킨</label>\n");
      out.write("                 <label for=\"checkbox8\">\n");
      out.write("                <input type=\"checkbox\" value=\"텍스쳐팩\" id=\"checkbox8\" name=\"utag\" class=\"tags\">텍스쳐팩</label>\n");
      out.write("                 <label for=\"checkbox9\">\n");
      out.write("                <input type=\"checkbox\" value=\"쉐이더\" id=\"checkbox9\" name=\"utag\" class=\"tags\">쉐이더</label>\n");
      out.write("               <label for=\"checkbox10\">\n");
      out.write("                <input type=\"checkbox\" value=\"귀여운 사진\" id=\"checkbox10\" name=\"utag\" class=\"tags\">귀여운 사진</label>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <button type=\"submit\" disabled=\"disabled\" id=\"formBtn\">완료</button>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("  \n");
      out.write("  \n");
      out.write("<div class=\"modal fade hidePrevented.bs.modal\" id=\"staticBackdrop\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("                  <div class=\"modal-dialog modal-lg modal-dialog-centered\">\n");
      out.write("                    <div class=\"modal-content\">\n");
      out.write("                      <div class=\"modal-header\">\n");
      out.write("                        <h1 class=\"modal-title fs-5\" id=\"staticBackdropLabel\">프로필 사진 설정</h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"modal-body\">\n");
      out.write("                        <div id=\"choiceImg\">\n");
      out.write("                          <img class=\"profile_img\" src=\"../../resources/images/profile/zombie.png\"  onclick=\"showPreview('../../resources/images/profile/zombie.png')\">\n");
      out.write("                          <img class=\"profile_img\" src=\"../../resources/images/profile/villager.png\"  onclick=\"showPreview('../../resources/images/profile/villager.png')\">\n");
      out.write("                          <img class=\"profile_img\" src=\"../../resources/images/profile/enderman.jpg\"  onclick=\"showPreview('../../resources/images/profile/enderman.jpg')\">\n");
      out.write("                          <img class=\"profile_img\" src=\"../../resources/images/profile/pig.jpg\"  onclick=\"showPreview('../../resources/images/profile/pig.jpg')\">\n");
      out.write("                          <img class=\"profile_img\" src=\"../../resources/images/profile/steve.jpg\"  onclick=\"showPreview('../../resources/images/profile/steve.jpg')\">\n");
      out.write("                          <img id=\"mypic\" src=\"../../resources/images/profile/24.png\" alt=\"Preview\" >\n");
      out.write("                          \n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<!-- HTML 코드 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../../resources/js/user/userJoin.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
